// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"quocbang/swagger-microservices/swagger/models"
)

// ChangePasswordHandlerFunc turns a function with the right signature into a change password handler
type ChangePasswordHandlerFunc func(ChangePasswordParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ChangePasswordHandlerFunc) Handle(params ChangePasswordParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ChangePasswordHandler interface for that can handle valid change password params
type ChangePasswordHandler interface {
	Handle(ChangePasswordParams, *models.Principal) middleware.Responder
}

// NewChangePassword creates a new http.Handler for the change password operation
func NewChangePassword(ctx *middleware.Context, handler ChangePasswordHandler) *ChangePassword {
	return &ChangePassword{Context: ctx, Handler: handler}
}

/* ChangePassword swagger:route PUT /user/change-password account changePassword

修改密碼(限MES帳號)

*/
type ChangePassword struct {
	Context *middleware.Context
	Handler ChangePasswordHandler
}

func (o *ChangePassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewChangePasswordParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ChangePasswordBody change password body
//
// swagger:model ChangePasswordBody
type ChangePasswordBody struct {

	// 原密碼
	// Required: true
	// Max Length: 10
	// Min Length: 6
	CurrentPassword *string `json:"currentPassword"`

	// 新密碼
	// Required: true
	// Max Length: 10
	// Min Length: 6
	NewPassword *string `json:"newPassword"`
}

// Validate validates this change password body
func (o *ChangePasswordBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCurrentPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ChangePasswordBody) validateCurrentPassword(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"currentPassword", "body", o.CurrentPassword); err != nil {
		return err
	}

	if err := validate.MinLength("body"+"."+"currentPassword", "body", *o.CurrentPassword, 6); err != nil {
		return err
	}

	if err := validate.MaxLength("body"+"."+"currentPassword", "body", *o.CurrentPassword, 10); err != nil {
		return err
	}

	return nil
}

func (o *ChangePasswordBody) validateNewPassword(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"newPassword", "body", o.NewPassword); err != nil {
		return err
	}

	if err := validate.MinLength("body"+"."+"newPassword", "body", *o.NewPassword, 6); err != nil {
		return err
	}

	if err := validate.MaxLength("body"+"."+"newPassword", "body", *o.NewPassword, 10); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this change password body based on context it is used
func (o *ChangePasswordBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ChangePasswordBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ChangePasswordBody) UnmarshalBinary(b []byte) error {
	var res ChangePasswordBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
