// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"quocbang/swagger-microservices/swagger/models"
)

// GetRoleListOKCode is the HTTP code returned for type GetRoleListOK
const GetRoleListOKCode int = 200

/*GetRoleListOK OK

swagger:response getRoleListOK
*/
type GetRoleListOK struct {

	/*
	  In: Body
	*/
	Payload *GetRoleListOKBody `json:"body,omitempty"`
}

// NewGetRoleListOK creates GetRoleListOK with default headers values
func NewGetRoleListOK() *GetRoleListOK {

	return &GetRoleListOK{}
}

// WithPayload adds the payload to the get role list o k response
func (o *GetRoleListOK) WithPayload(payload *GetRoleListOKBody) *GetRoleListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get role list o k response
func (o *GetRoleListOK) SetPayload(payload *GetRoleListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRoleListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRoleListDefault Unexpected error

swagger:response getRoleListDefault
*/
type GetRoleListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRoleListDefault creates GetRoleListDefault with default headers values
func NewGetRoleListDefault(code int) *GetRoleListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRoleListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get role list default response
func (o *GetRoleListDefault) WithStatusCode(code int) *GetRoleListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get role list default response
func (o *GetRoleListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get role list default response
func (o *GetRoleListDefault) WithPayload(payload *models.Error) *GetRoleListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get role list default response
func (o *GetRoleListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRoleListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
