// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"quocbang/swagger-microservices/swagger/models"
)

// ListUnauthorizedAccountOKCode is the HTTP code returned for type ListUnauthorizedAccountOK
const ListUnauthorizedAccountOKCode int = 200

/*ListUnauthorizedAccountOK OK

swagger:response listUnauthorizedAccountOK
*/
type ListUnauthorizedAccountOK struct {

	/*
	  In: Body
	*/
	Payload *ListUnauthorizedAccountOKBody `json:"body,omitempty"`
}

// NewListUnauthorizedAccountOK creates ListUnauthorizedAccountOK with default headers values
func NewListUnauthorizedAccountOK() *ListUnauthorizedAccountOK {

	return &ListUnauthorizedAccountOK{}
}

// WithPayload adds the payload to the list unauthorized account o k response
func (o *ListUnauthorizedAccountOK) WithPayload(payload *ListUnauthorizedAccountOKBody) *ListUnauthorizedAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list unauthorized account o k response
func (o *ListUnauthorizedAccountOK) SetPayload(payload *ListUnauthorizedAccountOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUnauthorizedAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListUnauthorizedAccountDefault Unexpected error

swagger:response listUnauthorizedAccountDefault
*/
type ListUnauthorizedAccountDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUnauthorizedAccountDefault creates ListUnauthorizedAccountDefault with default headers values
func NewListUnauthorizedAccountDefault(code int) *ListUnauthorizedAccountDefault {
	if code <= 0 {
		code = 500
	}

	return &ListUnauthorizedAccountDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list unauthorized account default response
func (o *ListUnauthorizedAccountDefault) WithStatusCode(code int) *ListUnauthorizedAccountDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list unauthorized account default response
func (o *ListUnauthorizedAccountDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list unauthorized account default response
func (o *ListUnauthorizedAccountDefault) WithPayload(payload *models.Error) *ListUnauthorizedAccountDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list unauthorized account default response
func (o *ListUnauthorizedAccountDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUnauthorizedAccountDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
