// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"quocbang/swagger-microservices/swagger/models"
)

// ListAuthorizedAccountOKCode is the HTTP code returned for type ListAuthorizedAccountOK
const ListAuthorizedAccountOKCode int = 200

/*ListAuthorizedAccountOK OK

swagger:response listAuthorizedAccountOK
*/
type ListAuthorizedAccountOK struct {

	/*
	  In: Body
	*/
	Payload *ListAuthorizedAccountOKBody `json:"body,omitempty"`
}

// NewListAuthorizedAccountOK creates ListAuthorizedAccountOK with default headers values
func NewListAuthorizedAccountOK() *ListAuthorizedAccountOK {

	return &ListAuthorizedAccountOK{}
}

// WithPayload adds the payload to the list authorized account o k response
func (o *ListAuthorizedAccountOK) WithPayload(payload *ListAuthorizedAccountOKBody) *ListAuthorizedAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list authorized account o k response
func (o *ListAuthorizedAccountOK) SetPayload(payload *ListAuthorizedAccountOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAuthorizedAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListAuthorizedAccountDefault Unexpected error

swagger:response listAuthorizedAccountDefault
*/
type ListAuthorizedAccountDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListAuthorizedAccountDefault creates ListAuthorizedAccountDefault with default headers values
func NewListAuthorizedAccountDefault(code int) *ListAuthorizedAccountDefault {
	if code <= 0 {
		code = 500
	}

	return &ListAuthorizedAccountDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list authorized account default response
func (o *ListAuthorizedAccountDefault) WithStatusCode(code int) *ListAuthorizedAccountDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list authorized account default response
func (o *ListAuthorizedAccountDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list authorized account default response
func (o *ListAuthorizedAccountDefault) WithPayload(payload *models.Error) *ListAuthorizedAccountDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list authorized account default response
func (o *ListAuthorizedAccountDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAuthorizedAccountDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
