// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewUpdateAccountAuthorizationParams creates a new UpdateAccountAuthorizationParams object
//
// There are no default values defined in the spec.
func NewUpdateAccountAuthorizationParams() UpdateAccountAuthorizationParams {

	return UpdateAccountAuthorizationParams{}
}

// UpdateAccountAuthorizationParams contains all the bound params for the update account authorization operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateAccountAuthorization
type UpdateAccountAuthorizationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Body UpdateAccountAuthorizationBody
	/*人員工號
	  Required: true
	  In: path
	*/
	EmployeeID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateAccountAuthorizationParams() beforehand.
func (o *UpdateAccountAuthorizationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body UpdateAccountAuthorizationBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}

	rEmployeeID, rhkEmployeeID, _ := route.Params.GetOK("employeeID")
	if err := o.bindEmployeeID(rEmployeeID, rhkEmployeeID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmployeeID binds and validates parameter EmployeeID from path.
func (o *UpdateAccountAuthorizationParams) bindEmployeeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.EmployeeID = raw

	return nil
}
