// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Department 部門資訊
//
// swagger:model Department
type Department struct {

	// 部門代號
	// Example: M2110
	ID string `json:"ID,omitempty"`

	// 部門OID
	OID string `json:"OID,omitempty"`
}

// Validate validates this department
func (m *Department) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this department based on context it is used
func (m *Department) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Department) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Department) UnmarshalBinary(b []byte) error {
	var res Department
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
