# Start Configurations
development_mode: false

ui_distribution_directory: "../ui/dist"

create_ui_configuration: false

# PDA WebService Endpoint
web_service_endpoint: ""

# Database Connection Settings
postgres:
  name: "kverp"
  address: "198.1.1.92"
  port: 5432
  username: "postgres"
  password: "kenda"
  schema: "kvmes"

# Active Directory Connection Settings
active_directory:
  host: ""
  port: 0
  base_dn: ""
  query_user: ""
  query_password: ""
  with_tls: false

# CORS Allowed Origins Setting
cors_allowed_origins:
  - "*"

# Set User Token Expiration
token_expired_in_seconds: 60000

# chinese_font_path: "../assets/fonts/AR MingtiM BIG-5.ttf"

font_path: "../../../../assets/fonts/kaiu.ttf"

#printers:
#  KU-P3122-PLY-CUT-1: ""
#station_function_config:
#  KU-P3122-PLY-CUT-1:
#    loadWorkOrder: "http://kumes.kenda.com.tw:8899/KU-P3122-PLY-CUT-1/notify/work-order/start"
#    closedWorkOrder: "http://kumes.kenda.com.tw:8899/KU-P3122-PLY-CUT-1/notify/work-order/closed"
#    bindResource: "http://kumes.kenda.com.tw:8899/KU-P3122-PLY-CUT-1/notify/resource/bind"
# Function Handlers Permission for access limitation
permissions:
  GET_SERVER_STATUS:
    - ADMINISTRATOR
  # 材料更改(舊程式)
  GET_BARCODE_INFO:
    - ADMINISTRATOR
    - INSPECTOR
  UPDATE_BARCODE:
    - ADMINISTRATOR
    - INSPECTOR
  GET_UPDATE_BARCODE_STATUS_LIST:
    - ADMINISTRATOR
    - INSPECTOR
  GET_EXTEND_DAYS:
    - ADMINISTRATOR
    - INSPECTOR
  GET_CONTROL_AREA_LIST:
    - ADMINISTRATOR
    - INSPECTOR
  GET_HOLD_REASON_LIST:
    - ADMINISTRATOR
    - INSPECTOR
  GET_PRODUCT_TYPE_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_PRODUCT_GROUP_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_PRODUCT_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_RECIPE_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 排產
  GET_PLAN_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  ADD_PLAN:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 派工單
  CREATE_STATION_SCHEDULING:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_STATION_SCHEDULING:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  UPDATE_STATION_SCHEDULING:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # DOWNLOAD_WORK_ORDER_RECIPE:
  #   - ROLE_UNSPECIFIED
  #   - ADMINISTRATOR
  # 機台
  GET_STATION_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 新增材料
  ADD_MATERIAL:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 庫存移轉
  GET_WAREHOUSE_INFO:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  WAREHOUSE_TRANSACTION:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 掛載材料
  GET_MATERIAL_RESOURCE_INFO:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_SITE_MATERIAL_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  BIND_RESOURCE:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 修改密碼
  CHANGE_USER_PASSWORD:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
    - LEADER
    - PLANNER
    - SCHEDULER
    - INSPECTOR
    - QUALITY_CONTROLLER
    - OPERATOR
    - BEARER
  # 載具維護
  LIST_CARRIER:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  CREATE_CARRIER:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  UPDATE_CARRIER:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  DELETE_CARRIER:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 配合表查詢
  GET_RECIPE_IDS:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_RECIPE_PROCESS_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 機台維護
  SITE_TYPE_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  SITE_SUBTYPE_LIST:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_STATION_INFO:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  CREATE_STATION:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  UPDATE_STATION_INFO:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  DELETE_STATION:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_STATION_STATE:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 帳號管理
  GET_ROLE_LIST:
    - ADMINISTRATOR
  LIST_AUTHORIZED_ACCOUNT:
    - ADMINISTRATOR
  LIST_UNAUTHORIZED_ACCOUNT:
    - ADMINISTRATOR
  CREATE_ACCOUNT:
    - ADMINISTRATOR
  UPDATE_ACCOUNT:
    - ADMINISTRATOR
  DELETE_ACCOUNT:
    - ADMINISTRATOR
  # 物料查詢
  GET_MATERIAL_RESOURCE_INFO_BY_TYPE:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_MATERIAL_STATUS:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_DEPARTMENT_IDS:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  # 分批物料
  SPLIT_MATERIAL:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  DOWNLOAD_MATERIAL_RESOURCE:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
# PDA 操作
  CHANGE_WORK_ORDER_STATUS:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_WORK_ORDERS:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_WORK_ORDER_INFORMATION:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_SITE_INFORMATION:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_TOOL_ID:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  FEED_COLLECT:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_STATIONS:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  SET_STATION_CONFIG:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  GET_STATION_CONFIG:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  LIST_STATION_SITES:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR
  PRINT_MATERIAL_RESOURCE:
    - ROLE_UNSPECIFIED
    - ADMINISTRATOR