// Code generated by go-swagger; DO NOT EDIT.

// Package restapi API Proposal for go-swagger-api
//
//  This is RESTful API specification for quocbang system.
//  The default response of each API endpoints are based on HTTP Status Code Standardization, e.g:
//    - 400 (Bad Request)
//    - 401 (Unauthorized)
//    - 403 (Forbidden)
//    - 408 (Request Timeout)
//    - 500 (Internal Server Error)
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /api
//  Version: 1.1.1
//  License: Copyright © 2023 by quocbang, All Rights Reserved
//  Contact: <quocbang@kenda.com.tw>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
