// Code generated by go-swagger; DO NOT EDIT.

package production

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetlimitaryParams creates a new GetlimitaryParams object
//
// There are no default values defined in the spec.
func NewGetlimitaryParams() GetlimitaryParams {

	return GetlimitaryParams{}
}

// GetlimitaryParams contains all the bound params for the getlimitary operation
// typically these are obtained from a http.Request
//
// swagger:parameters Getlimitary
type GetlimitaryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ProductType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetlimitaryParams() beforehand.
func (o *GetlimitaryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rProductType, rhkProductType, _ := route.Params.GetOK("productType")
	if err := o.bindProductType(rProductType, rhkProductType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindProductType binds and validates parameter ProductType from path.
func (o *GetlimitaryParams) bindProductType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ProductType = raw

	return nil
}
