// Code generated by go-swagger; DO NOT EDIT.

package production

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"quocbang/swagger-microservices/swagger/models"
)

// GetlimitaryHandlerFunc turns a function with the right signature into a getlimitary handler
type GetlimitaryHandlerFunc func(GetlimitaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetlimitaryHandlerFunc) Handle(params GetlimitaryParams) middleware.Responder {
	return fn(params)
}

// GetlimitaryHandler interface for that can handle valid getlimitary params
type GetlimitaryHandler interface {
	Handle(GetlimitaryParams) middleware.Responder
}

// NewGetlimitary creates a new http.Handler for the getlimitary operation
func NewGetlimitary(ctx *middleware.Context, handler GetlimitaryHandler) *Getlimitary {
	return &Getlimitary{Context: ctx, Handler: handler}
}

/* Getlimitary swagger:route GET /limitary/{productType} production getlimitary

get limitary hour from database

*/
type Getlimitary struct {
	Context *middleware.Context
	Handler GetlimitaryHandler
}

func (o *Getlimitary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetlimitaryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetlimitaryOKBody getlimitary o k body
//
// swagger:model GetlimitaryOKBody
type GetlimitaryOKBody struct {

	// data
	Data *models.Limitary `json:"data,omitempty"`
}

// Validate validates this getlimitary o k body
func (o *GetlimitaryOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetlimitaryOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getlimitaryOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this getlimitary o k body based on the context it is used
func (o *GetlimitaryOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetlimitaryOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getlimitaryOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetlimitaryOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetlimitaryOKBody) UnmarshalBinary(b []byte) error {
	var res GetlimitaryOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
