// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckServerStatusHandlerFunc turns a function with the right signature into a check server status handler
type CheckServerStatusHandlerFunc func(CheckServerStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckServerStatusHandlerFunc) Handle(params CheckServerStatusParams) middleware.Responder {
	return fn(params)
}

// CheckServerStatusHandler interface for that can handle valid check server status params
type CheckServerStatusHandler interface {
	Handle(CheckServerStatusParams) middleware.Responder
}

// NewCheckServerStatus creates a new http.Handler for the check server status operation
func NewCheckServerStatus(ctx *middleware.Context, handler CheckServerStatusHandler) *CheckServerStatus {
	return &CheckServerStatus{Context: ctx, Handler: handler}
}

/* CheckServerStatus swagger:route GET /server/status checkServerStatus

檢查server狀態用

*/
type CheckServerStatus struct {
	Context *middleware.Context
	Handler CheckServerStatusHandler
}

func (o *CheckServerStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckServerStatusParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
