// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"quocbang/swagger-microservices/swagger/models"
	"quocbang/swagger-microservices/swagger/restapi/operations/account"
	"quocbang/swagger-microservices/swagger/restapi/operations/production"
)

// NewSwaggerMicroservicesAPI creates a new SwaggerMicroservices instance
func NewSwaggerMicroservicesAPI(spec *loads.Document) *SwaggerMicroservicesAPI {
	return &SwaggerMicroservicesAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		AccountChangePasswordHandler: account.ChangePasswordHandlerFunc(func(params account.ChangePasswordParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.ChangePassword has not yet been implemented")
		}),
		CheckServerStatusHandler: CheckServerStatusHandlerFunc(func(params CheckServerStatusParams) middleware.Responder {
			return middleware.NotImplemented("operation CheckServerStatus has not yet been implemented")
		}),
		AccountCreateAccountAuthorizationHandler: account.CreateAccountAuthorizationHandlerFunc(func(params account.CreateAccountAuthorizationParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.CreateAccountAuthorization has not yet been implemented")
		}),
		AccountDeleteAccountHandler: account.DeleteAccountHandlerFunc(func(params account.DeleteAccountParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.DeleteAccount has not yet been implemented")
		}),
		AccountGetRoleListHandler: account.GetRoleListHandlerFunc(func(params account.GetRoleListParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.GetRoleList has not yet been implemented")
		}),
		ProductionGetlimitaryHandler: production.GetlimitaryHandlerFunc(func(params production.GetlimitaryParams) middleware.Responder {
			return middleware.NotImplemented("operation production.Getlimitary has not yet been implemented")
		}),
		AccountListAuthorizedAccountHandler: account.ListAuthorizedAccountHandlerFunc(func(params account.ListAuthorizedAccountParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.ListAuthorizedAccount has not yet been implemented")
		}),
		AccountListUnauthorizedAccountHandler: account.ListUnauthorizedAccountHandlerFunc(func(params account.ListUnauthorizedAccountParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.ListUnauthorizedAccount has not yet been implemented")
		}),
		AccountLoginHandler: account.LoginHandlerFunc(func(params account.LoginParams) middleware.Responder {
			return middleware.NotImplemented("operation account.Login has not yet been implemented")
		}),
		AccountLogoutHandler: account.LogoutHandlerFunc(func(params account.LogoutParams) middleware.Responder {
			return middleware.NotImplemented("operation account.Logout has not yet been implemented")
		}),
		AccountUpdateAccountAuthorizationHandler: account.UpdateAccountAuthorizationHandlerFunc(func(params account.UpdateAccountAuthorizationParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation account.UpdateAccountAuthorization has not yet been implemented")
		}),

		// Applies when the "x-api-auth-key" header is set
		APIKeyAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (api_key) x-api-auth-key from header param [x-api-auth-key] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*SwaggerMicroservicesAPI This is RESTful API specification for quocbang system.
The default response of each API endpoints are based on HTTP Status Code Standardization, e.g:
  - 400 (Bad Request)
  - 401 (Unauthorized)
  - 403 (Forbidden)
  - 408 (Request Timeout)
  - 500 (Internal Server Error)
*/
type SwaggerMicroservicesAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// APIKeyAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key x-api-auth-key provided in the header
	APIKeyAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// AccountChangePasswordHandler sets the operation handler for the change password operation
	AccountChangePasswordHandler account.ChangePasswordHandler
	// CheckServerStatusHandler sets the operation handler for the check server status operation
	CheckServerStatusHandler CheckServerStatusHandler
	// AccountCreateAccountAuthorizationHandler sets the operation handler for the create account authorization operation
	AccountCreateAccountAuthorizationHandler account.CreateAccountAuthorizationHandler
	// AccountDeleteAccountHandler sets the operation handler for the delete account operation
	AccountDeleteAccountHandler account.DeleteAccountHandler
	// AccountGetRoleListHandler sets the operation handler for the get role list operation
	AccountGetRoleListHandler account.GetRoleListHandler
	// ProductionGetlimitaryHandler sets the operation handler for the getlimitary operation
	ProductionGetlimitaryHandler production.GetlimitaryHandler
	// AccountListAuthorizedAccountHandler sets the operation handler for the list authorized account operation
	AccountListAuthorizedAccountHandler account.ListAuthorizedAccountHandler
	// AccountListUnauthorizedAccountHandler sets the operation handler for the list unauthorized account operation
	AccountListUnauthorizedAccountHandler account.ListUnauthorizedAccountHandler
	// AccountLoginHandler sets the operation handler for the login operation
	AccountLoginHandler account.LoginHandler
	// AccountLogoutHandler sets the operation handler for the logout operation
	AccountLogoutHandler account.LogoutHandler
	// AccountUpdateAccountAuthorizationHandler sets the operation handler for the update account authorization operation
	AccountUpdateAccountAuthorizationHandler account.UpdateAccountAuthorizationHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *SwaggerMicroservicesAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *SwaggerMicroservicesAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *SwaggerMicroservicesAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SwaggerMicroservicesAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SwaggerMicroservicesAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SwaggerMicroservicesAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SwaggerMicroservicesAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SwaggerMicroservicesAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SwaggerMicroservicesAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SwaggerMicroservicesAPI
func (o *SwaggerMicroservicesAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.APIKeyAuth == nil {
		unregistered = append(unregistered, "XAPIAuthKeyAuth")
	}

	if o.AccountChangePasswordHandler == nil {
		unregistered = append(unregistered, "account.ChangePasswordHandler")
	}
	if o.CheckServerStatusHandler == nil {
		unregistered = append(unregistered, "CheckServerStatusHandler")
	}
	if o.AccountCreateAccountAuthorizationHandler == nil {
		unregistered = append(unregistered, "account.CreateAccountAuthorizationHandler")
	}
	if o.AccountDeleteAccountHandler == nil {
		unregistered = append(unregistered, "account.DeleteAccountHandler")
	}
	if o.AccountGetRoleListHandler == nil {
		unregistered = append(unregistered, "account.GetRoleListHandler")
	}
	if o.ProductionGetlimitaryHandler == nil {
		unregistered = append(unregistered, "production.GetlimitaryHandler")
	}
	if o.AccountListAuthorizedAccountHandler == nil {
		unregistered = append(unregistered, "account.ListAuthorizedAccountHandler")
	}
	if o.AccountListUnauthorizedAccountHandler == nil {
		unregistered = append(unregistered, "account.ListUnauthorizedAccountHandler")
	}
	if o.AccountLoginHandler == nil {
		unregistered = append(unregistered, "account.LoginHandler")
	}
	if o.AccountLogoutHandler == nil {
		unregistered = append(unregistered, "account.LogoutHandler")
	}
	if o.AccountUpdateAccountAuthorizationHandler == nil {
		unregistered = append(unregistered, "account.UpdateAccountAuthorizationHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SwaggerMicroservicesAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SwaggerMicroservicesAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "api_key":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.APIKeyAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *SwaggerMicroservicesAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *SwaggerMicroservicesAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *SwaggerMicroservicesAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SwaggerMicroservicesAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the swagger microservices API
func (o *SwaggerMicroservicesAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SwaggerMicroservicesAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/user/change-password"] = account.NewChangePassword(o.context, o.AccountChangePasswordHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/server/status"] = NewCheckServerStatus(o.context, o.CheckServerStatusHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/account/authorization"] = account.NewCreateAccountAuthorization(o.context, o.AccountCreateAccountAuthorizationHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/account/authorization/{employeeID}"] = account.NewDeleteAccount(o.context, o.AccountDeleteAccountHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/role-list"] = account.NewGetRoleList(o.context, o.AccountGetRoleListHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/limitary/{productType}"] = production.NewGetlimitary(o.context, o.ProductionGetlimitaryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/authorized/department-oid/{departmentOID}"] = account.NewListAuthorizedAccount(o.context, o.AccountListAuthorizedAccountHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/unauthorized/department-oid/{departmentOID}"] = account.NewListUnauthorizedAccount(o.context, o.AccountListUnauthorizedAccountHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/login"] = account.NewLogin(o.context, o.AccountLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user/logout"] = account.NewLogout(o.context, o.AccountLogoutHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/account/authorization/{employeeID}"] = account.NewUpdateAccountAuthorization(o.context, o.AccountUpdateAccountAuthorizationHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SwaggerMicroservicesAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SwaggerMicroservicesAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SwaggerMicroservicesAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SwaggerMicroservicesAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *SwaggerMicroservicesAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
